
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

//Program:        PositiveMaturityApp
//Panel:          Cartegories
//Description:    File controls the Categories Panel of the application. Additions or changes to the layout and feel
//                of the panel can be made from this file
//Author:         Jauan Davis
//Revised:        9/09/2013
//Language:       Java
//IDE:            NetBeans 7.2
//************************************************************************************************************
public class ServicesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServicesPanel
     */
    Container guiFrame;
    DatabaseConnection db= new DatabaseConnection();
    public ServicesPanel() {
        initComponents();
        
        Categorytable.setModel(db.getbenefitsTable());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Categorytable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deletebutton = new javax.swing.JButton();
        categoryagencylist = new javax.swing.JButton();
        Viewinfobutton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 28)); // NOI18N
        jLabel1.setText("Category/Service");

        Categorytable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Categorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        Categorytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategorytableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Categorytable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setText("ENHANCE");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel3.setText("EMPOWER");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel4.setText("ENGAGE");

        deletebutton.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        categoryagencylist.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        categoryagencylist.setText("Agencys associated with category");
        categoryagencylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryagencylistActionPerformed(evt);
            }
        });

        Viewinfobutton.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Viewinfobutton.setText("View Info");
        Viewinfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewinfobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(852, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Viewinfobutton)
                        .addGap(18, 18, 18)
                        .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryagencylist))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryagencylist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Viewinfobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        int row = Categorytable.getSelectedRow();
        
        category c= new category();
        c.setName((String)Categorytable.getValueAt(row,0));
         String output= "Do you want to delete this agency? ";
        output += c.getName();
        if(JOptionPane.showConfirmDialog(this, output, "Confirm Category delete?", JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION) {
        db.deletecategory(c);
        Categorytable.setModel(db.getbenefitsTable());
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void categoryagencylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryagencylistActionPerformed
        // TODO add your handling code here:
        int row= Categorytable.getSelectedRow();
        String categoryname=((String)Categorytable.getModel().getValueAt(row, 0));
        CategorySearch categoryagencylist = new CategorySearch(guiFrame,true,categoryname);
        categoryagencylist.setVisible(true);
    }//GEN-LAST:event_categoryagencylistActionPerformed

    private void ViewinfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewinfobuttonActionPerformed
        // TODO add your handling code here:
        int row= Categorytable.getSelectedRow();
        String categoryname=((String)Categorytable.getModel().getValueAt(row, 0));
        ViewCategoryInfo categoryinfo= new ViewCategoryInfo(guiFrame,true,categoryname);
        categoryinfo.setVisible(true);
        categoryinfo.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e) {
                Categorytable.setModel(db.getbenefitsTable());
            }
        });
        
    }//GEN-LAST:event_ViewinfobuttonActionPerformed

    private void CategorytableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategorytableMouseEntered
        // TODO add your handling code here:
        Categorytable.setModel(db.getbenefitsTable());
    }//GEN-LAST:event_CategorytableMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Categorytable;
    private javax.swing.JButton Viewinfobutton;
    private javax.swing.JButton categoryagencylist;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
